export const SEARCH_PLACES = 'SEARCH_PLACES';
export const GO_TO_PLACE = 'GO_TO_PLACE';
export const FETCH_FEEDS = 'FETCH_FEEDS';
export const FETCH_FAVS = 'FETCH_FAVS';
export const FETCH_SEARCH_HISTORY = 'FETCH_SEARCH_HISTORY';
export const SAVE_SEARCH_HISTORY = 'SAVE_SEARCH_HISTORY';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SWITCH_TO_MEDIA = 'SWITCH_TO_MEDIA';
export const SAVE_FAV = 'SAVE_FAV';
export const DELETE_ALL_HISTORY = 'DELETE_ALL_HISTORY';
export const DELETE_ALL_FAV = 'DELETE_ALL_FAV';
export const CHANGE_MOBILE_VIEW = 'CHANGE_MOBILE_VIEW';

